version: 2
jobs:
    test:
        docker:
            - image: circleci/node:10
        steps:
            - run:
                name: versions
                command: |
                  node --version
                  npm --version
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Lint
                command: npm run lint
            - run:
                name: Test
                command: npm test
workflows:
    version: 2
    test:
        jobs:
            - test
